"""empty message

Revision ID: ceb49c357379
Revises: 
Create Date: 2025-03-23 09:46:00.074227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceb49c357379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('func')
    with op.batch_alter_table('help_keyword', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('help_keyword')
    op.drop_table('event')
    op.drop_table('time_zone_transition')
    op.drop_table('procs_priv')
    op.drop_table('time_zone_leap_second')
    op.drop_table('tables_priv')
    op.drop_table('plugin')
    op.drop_table('host')
    op.drop_table('proc')
    with op.batch_alter_table('help_category', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('help_category')
    op.drop_table('user')
    op.drop_table('db')
    op.drop_table('slow_log')
    op.drop_table('columns_priv')
    op.drop_table('help_relation')
    op.drop_table('time_zone_name')
    op.drop_table('proxies_priv')
    op.drop_table('ndb_binlog_index')
    op.drop_table('time_zone_transition_type')
    with op.batch_alter_table('help_topic', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('help_topic')
    op.drop_table('time_zone')
    op.drop_table('servers')
    op.drop_table('general_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_log',
    sa.Column('event_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('thread_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('command_type', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('argument', mysql.MEDIUMTEXT(), nullable=False),
    comment='General log',
    mysql_comment='General log',
    mysql_default_charset='utf8',
    mysql_engine='CSV'
    )
    op.create_table('servers',
    sa.Column('Server_name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Host', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Username', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Password', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Port', mysql.INTEGER(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Socket', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Wrapper', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Owner', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Server_name'),
    comment='MySQL Foreign Servers table',
    mysql_comment='MySQL Foreign Servers table',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('time_zone',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Use_leap_seconds', mysql.ENUM('Y', 'N'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id'),
    comment='Time zones',
    mysql_comment='Time zones',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('help_topic',
    sa.Column('help_topic_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('help_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('example', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_topic_id'),
    comment='help topics',
    mysql_comment='help topics',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('help_topic', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('time_zone_transition_type',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Offset', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Is_DST', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Abbreviation', mysql.CHAR(length=8), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_type_id'),
    comment='Time zone transition types',
    mysql_comment='Time zone transition types',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('ndb_binlog_index',
    sa.Column('Position', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('File', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('epoch', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('inserts', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('updates', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('deletes', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('schemaops', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('epoch'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('proxies_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_user', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('With_grant', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Proxied_host', 'Proxied_user'),
    comment='User proxy privileges',
    mysql_collate='utf8_bin',
    mysql_comment='User proxy privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('time_zone_name',
    sa.Column('Name', mysql.CHAR(length=64), nullable=False),
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Name'),
    comment='Time zone names',
    mysql_comment='Time zone names',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('help_relation',
    sa.Column('help_topic_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('help_keyword_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id', 'help_topic_id'),
    comment='keyword-topic relation',
    mysql_comment='keyword-topic relation',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('columns_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Column_priv', mysql.SET('Select', 'Insert', 'Update', 'References', charset='utf8'), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Table_name', 'Column_name'),
    comment='Column privileges',
    mysql_collate='utf8_bin',
    mysql_comment='Column privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('slow_log',
    sa.Column('start_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('query_time', mysql.TIME(), nullable=False),
    sa.Column('lock_time', mysql.TIME(), nullable=False),
    sa.Column('rows_sent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rows_examined', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('db', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('last_insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sql_text', mysql.MEDIUMTEXT(), nullable=False),
    comment='Slow log',
    mysql_comment='Slow log',
    mysql_default_charset='utf8',
    mysql_engine='CSV'
    )
    op.create_table('db',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User'),
    comment='Database privileges',
    mysql_collate='utf8_bin',
    mysql_comment='Database privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('user',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Password', mysql.CHAR(charset='latin1', collation='latin1_bin', length=41), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Reload_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Shutdown_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Process_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('File_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_db_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Super_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_slave_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_client_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_user_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tablespace_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('ssl_type', mysql.ENUM('', 'ANY', 'X509', 'SPECIFIED'), server_default=sa.text("''"), nullable=False),
    sa.Column('ssl_cipher', sa.BLOB(), nullable=False),
    sa.Column('x509_issuer', sa.BLOB(), nullable=False),
    sa.Column('x509_subject', sa.BLOB(), nullable=False),
    sa.Column('max_questions', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_updates', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_user_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('plugin', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=True),
    sa.Column('authentication_string', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.PrimaryKeyConstraint('Host', 'User'),
    comment='Users and global privileges',
    mysql_collate='utf8_bin',
    mysql_comment='Users and global privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('help_category',
    sa.Column('help_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('parent_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_category_id'),
    comment='help categories',
    mysql_comment='help categories',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('help_category', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('proc',
    sa.Column('db', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('FUNCTION', 'PROCEDURE'), nullable=False),
    sa.Column('specific_name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('language', mysql.ENUM('SQL'), server_default=sa.text("'SQL'"), nullable=False),
    sa.Column('sql_data_access', mysql.ENUM('CONTAINS_SQL', 'NO_SQL', 'READS_SQL_DATA', 'MODIFIES_SQL_DATA'), server_default=sa.text("'CONTAINS_SQL'"), nullable=False),
    sa.Column('is_deterministic', mysql.ENUM('YES', 'NO'), server_default=sa.text("'NO'"), nullable=False),
    sa.Column('security_type', mysql.ENUM('INVOKER', 'DEFINER'), server_default=sa.text("'DEFINER'"), nullable=False),
    sa.Column('param_list', sa.BLOB(), nullable=False),
    sa.Column('returns', mysql.LONGBLOB(), nullable=False),
    sa.Column('body', mysql.LONGBLOB(), nullable=False),
    sa.Column('definer', mysql.CHAR(charset='utf8', collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('sql_mode', mysql.SET('REAL_AS_FLOAT', 'PIPES_AS_CONCAT', 'ANSI_QUOTES', 'IGNORE_SPACE', 'NOT_USED', 'ONLY_FULL_GROUP_BY', 'NO_UNSIGNED_SUBTRACTION', 'NO_DIR_IN_CREATE', 'POSTGRESQL', 'ORACLE', 'MSSQL', 'DB2', 'MAXDB', 'NO_KEY_OPTIONS', 'NO_TABLE_OPTIONS', 'NO_FIELD_OPTIONS', 'MYSQL323', 'MYSQL40', 'ANSI', 'NO_AUTO_VALUE_ON_ZERO', 'NO_BACKSLASH_ESCAPES', 'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES', 'NO_ZERO_IN_DATE', 'NO_ZERO_DATE', 'INVALID_DATES', 'ERROR_FOR_DIVISION_BY_ZERO', 'TRADITIONAL', 'NO_AUTO_CREATE_USER', 'HIGH_NOT_PRECEDENCE', 'NO_ENGINE_SUBSTITUTION', 'PAD_CHAR_TO_FULL_LENGTH'), server_default=sa.text("''"), nullable=False),
    sa.Column('comment', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('character_set_client', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('collation_connection', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('db_collation', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('body_utf8', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('db', 'name', 'type'),
    comment='Stored Procedures',
    mysql_comment='Stored Procedures',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('host',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db'),
    comment='Host privileges;  Merged with database privileges',
    mysql_collate='utf8_bin',
    mysql_comment='Host privileges;  Merged with database privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('plugin',
    sa.Column('name', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('dl', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    comment='MySQL plugins',
    mysql_comment='MySQL plugins',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('tables_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Table_priv', mysql.SET('Select', 'Insert', 'Update', 'Delete', 'Create', 'Drop', 'Grant', 'References', 'Index', 'Alter', 'Create View', 'Show view', 'Trigger', charset='utf8'), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_priv', mysql.SET('Select', 'Insert', 'Update', 'References', charset='utf8'), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Table_name'),
    comment='Table privileges',
    mysql_collate='utf8_bin',
    mysql_comment='Table privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('time_zone_leap_second',
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Correction', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Transition_time'),
    comment='Leap seconds information for time zones',
    mysql_comment='Leap seconds information for time zones',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('procs_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_name', mysql.CHAR(charset='utf8', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_type', mysql.ENUM('FUNCTION', 'PROCEDURE'), nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('Proc_priv', mysql.SET('Execute', 'Alter Routine', 'Grant', charset='utf8'), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Routine_name', 'Routine_type'),
    comment='Procedure privileges',
    mysql_collate='utf8_bin',
    mysql_comment='Procedure privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('time_zone_transition',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_time'),
    comment='Time zone transitions',
    mysql_comment='Time zone transitions',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('event',
    sa.Column('db', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('body', mysql.LONGBLOB(), nullable=False),
    sa.Column('definer', mysql.CHAR(charset='utf8', collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('execute_at', mysql.DATETIME(), nullable=True),
    sa.Column('interval_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('interval_field', mysql.ENUM('YEAR', 'QUARTER', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'WEEK', 'SECOND', 'MICROSECOND', 'YEAR_MONTH', 'DAY_HOUR', 'DAY_MINUTE', 'DAY_SECOND', 'HOUR_MINUTE', 'HOUR_SECOND', 'MINUTE_SECOND', 'DAY_MICROSECOND', 'HOUR_MICROSECOND', 'MINUTE_MICROSECOND', 'SECOND_MICROSECOND'), nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('last_executed', mysql.DATETIME(), nullable=True),
    sa.Column('starts', mysql.DATETIME(), nullable=True),
    sa.Column('ends', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM('ENABLED', 'DISABLED', 'SLAVESIDE_DISABLED'), server_default=sa.text("'ENABLED'"), nullable=False),
    sa.Column('on_completion', mysql.ENUM('DROP', 'PRESERVE'), server_default=sa.text("'DROP'"), nullable=False),
    sa.Column('sql_mode', mysql.SET('REAL_AS_FLOAT', 'PIPES_AS_CONCAT', 'ANSI_QUOTES', 'IGNORE_SPACE', 'NOT_USED', 'ONLY_FULL_GROUP_BY', 'NO_UNSIGNED_SUBTRACTION', 'NO_DIR_IN_CREATE', 'POSTGRESQL', 'ORACLE', 'MSSQL', 'DB2', 'MAXDB', 'NO_KEY_OPTIONS', 'NO_TABLE_OPTIONS', 'NO_FIELD_OPTIONS', 'MYSQL323', 'MYSQL40', 'ANSI', 'NO_AUTO_VALUE_ON_ZERO', 'NO_BACKSLASH_ESCAPES', 'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES', 'NO_ZERO_IN_DATE', 'NO_ZERO_DATE', 'INVALID_DATES', 'ERROR_FOR_DIVISION_BY_ZERO', 'TRADITIONAL', 'NO_AUTO_CREATE_USER', 'HIGH_NOT_PRECEDENCE', 'NO_ENGINE_SUBSTITUTION', 'PAD_CHAR_TO_FULL_LENGTH'), server_default=sa.text("''"), nullable=False),
    sa.Column('comment', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('originator', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('time_zone', mysql.CHAR(charset='latin1', length=64), server_default=sa.text("'SYSTEM'"), nullable=False),
    sa.Column('character_set_client', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('collation_connection', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('db_collation', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('body_utf8', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('db', 'name'),
    comment='Events',
    mysql_comment='Events',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('help_keyword',
    sa.Column('help_keyword_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id'),
    comment='help keywords',
    mysql_comment='help keywords',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('help_keyword', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('func',
    sa.Column('name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('ret', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('dl', mysql.CHAR(collation='utf8_bin', length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('function', 'aggregate'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    comment='User defined functions',
    mysql_collate='utf8_bin',
    mysql_comment='User defined functions',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
